export const PROFILE_SERVICE = 'PROFILE_SERVICE';
export const PROFILE_REPOSITORY = 'PROFILE_REPOSITORY';
export const PARTNERSHIP_SERVICE = 'PARTNERSHIP_SERVICE';
export const PARTNERSHIP_REPOSITORY = 'PARTNERSHIP_REPOSITORY';
